package com.mcajben.animation_skipper;

import java.util.Random;

public class DisplayTextFactory {
    private static final Random rand = new Random();
    private static final String[] TEXTS = {
            "{S} LATER",
            "{P} LATER",
            "{S} PASSES",
            "{P} PASS",
            "AFTER {S}",
            "AFTER {P}",
    };
    private static final String[] SINGULAR_TIMES = {
            "NO TIME",
            "A LITTLE TIME",
            "SOME TIME",
            "PLENTY OF TIME",
            "A GOOD DEAL OF TIME",
            "A GREAT DEAL OF TIME",
            "A LOT OF TIME",
            "A WHOLE LOT OF TIME",
            "ONE SECOND",
            "ONE MINUTE",
            "ONE HOUR",
            "ONE DAY",
            "ONE WEEK",
            "ONE MONTH",
            "ONE YEAR",
            "ONE DECADE",
            "ONE CENTURY",
            "ONE ETERNITY",
    };
    private static final String[] PLURAL_TIMES = {
            "{N} SECONDS",
            "{N} MINUTES",
            "{N} HOURS",
            "{N} DAYS",
            "{N} WEEKS",
            "{N} MONTHS",
            "{N} YEARS",
            "{N} DECADES",
            "{N} CENTURIES",
    };
    private static final String[] PLURAL_NUMBERS = {
            "TWO",
            "THREE",
            "FOUR",
            "FIVE",
            "SIX",
            "SEVEN",
            "EIGHT",
            "NINE",
            "TEN",
            "ELEVEN",
            "TWELVE",
            "THIRTEEN",
            "FOURTEEN",
            "FIFTEEN",
            "3.1415926",
            "SIX-SEVEN",
    };

    /**
     * Attempt to get a random text string that is different from {@code previousText}
     * @param previousText A previous random text that was generated by this function
     * @return Either a new random text, or the {@code previousText} (very unlikely)
     */
    public static String getRandomText(String previousText) {
        int attempt = 0;
        String randomText;

        do {
            randomText = getRandomText();
            attempt += 1;
        } while (attempt < 10 && randomText.equals(previousText));

        return randomText;
    }

    private static String getRandomText() {
        if (rand.nextInt(1_000_000) == 0) {
            // Special RNG Text
            return "YOU DIED";
        }

        String randomText = TEXTS[rand.nextInt(TEXTS.length)];

        if (randomText.contains("{S}")) {
            randomText = randomText.replace("{S}", SINGULAR_TIMES[rand.nextInt(SINGULAR_TIMES.length)]);
        }
        if (randomText.contains("{P}")) {
            randomText = randomText.replace("{P}", PLURAL_TIMES[rand.nextInt(PLURAL_TIMES.length)]);
        }
        if (randomText.contains("{N}")) {
            randomText = randomText.replace("{N}", PLURAL_NUMBERS[rand.nextInt(PLURAL_NUMBERS.length)]);
        }

        return randomText;
    }
}
